# docker-compose.yml
version: '3.8'
services:
    db:
        image: "postgres" # use latest official postgres version
        ports:
            - 5432:5432
        restart: always
        env_file:
            - backend/.env
        volumes:
            - postgres-db:/var/lib/postgresql/data # persist data even if container shuts down
    api:
        build:
            context: backend/
            dockerfile: api.Dockerfile
        image: task-planner-api
        depends_on:
            - "db"
        env_file:
            - backend/.env
        ports:
            - "5000:5000"
    frontend:
        build:
            context: frontend/
            dockerfile: frontend.Dockerfile
        image: task-planner-frontend
        ports:
            - "3000:80"
        depends_on:
            - "db"
volumes:
    postgres-db:
