"""empty message

Revision ID: 8b8c631bf854
Revises: 06a90531c838
Create Date: 2022-02-06 20:07:37.950101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8c631bf854'
down_revision = '06a90531c838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lists', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.drop_column('lists', 'owner_id')
    # ### end Alembic commands ###
